---
- name: Enable hostname resolve for the application server
  lineinfile:
    path: /etc/hosts
    line: "{{ sap_host }} {{ sap_hostname }}"
  when: (sap_host is defined) and (sap_hostname is defined)
...
