#### Ansible inventory.
resource "local_file" "ansible_inventory" {
  depends_on = [ module.app-vsi ]
  content = <<-DOC
all:
  hosts:
    db_host:
      ansible_host: "${data.ibm_is_instance.db-vsi.primary_network_interface[0].primary_ip[0].address}"
    app_host:
      ansible_host: "${data.ibm_is_instance.app-vsi.primary_network_interface[0].primary_ip[0].address}"
    DOC
  filename = "ansible/inventory.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible_sapnwapp-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_ascs_instance_number: "${var.sap_ascs_instance_number}"
sap_ci_instance_number: "${var.sap_ci_instance_number}"
sap_main_password: "${var.sap_main_password}"
db_host: "${module.db-vsi.PRIVATE-IP}"
db_hostname: "${var.DB-HOSTNAME}"
sap_profile: "${var.APP-PROFILE}"
...
    DOC
  filename = "ansible/sapnwapp-vars.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "app_ansible_sapnwascs-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_ascs_instance_number: "${var.sap_ascs_instance_number}"
sap_ci_instance_number: "${var.sap_ci_instance_number}"
sap_main_password: "${var.sap_main_password}"

#SAP Installation kit path
kit_sapcar_file: "${var.kit_sapcar_file}"
kit_swpm_file: "${var.kit_swpm_file}"
kit_sapexe_file: "${var.kit_sapexe_file}"
kit_sapexedb_file: "${var.kit_sapexedb_file}"
kit_igsexe_file: "${var.kit_igsexe_file}"
kit_igshelper_file: "${var.kit_igshelper_file}"
kit_saphotagent_file: "${var.kit_saphotagent_file}"
kit_export_dir: "${var.kit_export_dir}"
...
    DOC
  filename = "ansible/sapnwascs-vars.yml"
}


# Export Terraform variable values to an Ansible var_file
resource "local_file" "db_ansible_sapnwdb-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_host: "${module.app-vsi.PRIVATE-IP}"
sap_hostname: "${var.APP-HOSTNAME}"
sap_ascs_instance_number: "${var.sap_ascs_instance_number}"
sap_main_password: "${var.sap_main_password}"

#SAP Installation kit path
kit_sapcar_file: "${var.kit_sapcar_file}"
kit_swpm_file: "${var.kit_swpm_file}"
kit_sapexe_file: "${var.kit_sapexe_file}"
kit_sapexedb_file: "${var.kit_sapexedb_file}"
kit_saphotagent_file: "${var.kit_saphotagent_file}"
kit_export_dir: "${var.kit_export_dir}"
kit_ase_file: "${var.kit_ase_file}"
...
    DOC
  filename = "ansible/sapnwdb-vars.yml"
}
