---
- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Import playbook variables
      include_vars: "sapnwdb-vars.yml"
  roles:
    - sapbasereq
    - asedbreq
    - asedbfs
    - asedbinst
...
